import { Role } from "@prisma/client";


export const usersMock = [
  {
    id: 1,
    name: 'Tony Reichert',
    role: Role.USER,
    password: '12345678',
    status: 'active',
    age: '29',
    avatar: '',
    email: 'tony.reichert@example.com',
  },
  {
    id: 2,
    name: 'Zoey Lang',
    role: Role.USER,
    password: '12345678',
    status: 'paused',
    age: '25',
    avatar: '',
    email: 'zoey.lang@example.com',
  },
  {
    id: 3,
    name: 'Jane Fisher',
    role: Role.ADMIN,
    password: '12345678',
    status: 'active',
    age: '22',
    avatar: '',
    email: 'jane.fisher@example.com',
  },
  {
    id: 4,
    name: 'William Howard',
    role: Role.USER,
    password: '12345678',
    status: 'vacation',
    age: '28',
    avatar: '',
    email: 'william.howard@example.com',
  },
  {
    id: 5,
    name: 'Kristen Copper',
    role: Role.USER,
    password: '12345678',
    status: 'active',
    age: '24',
    avatar: '',
    email: 'kristen.cooper@example.com',
  },
  {
    id: 6,
    name: 'Brian Kim',
    role: Role.USER,
    password: '12345678',
    age: '29',
    avatar: '',
    email: 'brian.kim@example.com',
    status: 'active',
  },
  {
    id: 7,
    name: 'Michael Hunt',
    role: Role.USER,
    password: '12345678',
    status: 'paused',
    age: '27',
    avatar: '',
    email: 'michael.hunt@example.com',
  },
  {
    id: 8,
    name: 'Samantha Brooks',
    role: Role.MANAGER,
    password: '12345678',
    status: 'active',
    age: '31',
    avatar: '',
    email: 'samantha.brooks@example.com',
  },
  {
    id: 9,
    name: 'Frank Harrison',
    role: Role.USER,
    password: '12345678',
    status: 'vacation',
    age: '33',
    avatar: '',
    email: 'frank.harrison@example.com',
  },
  {
    id: 10,
    name: 'Emma Adams',
    role: Role.USER,
    password: '12345678',
    status: 'active',
    age: '35',
    avatar: '',
    email: 'emma.adams@example.com',
  },
  {
    id: 11,
    name: 'Brandon Stevens',
    role: Role.USER,
    password: '12345678',
    status: 'active',
    age: '22',
    avatar: '',
    email: 'brandon.stevens@example.com',
  },
  {
    id: 12,
    name: 'Megan Richards',
    role: Role.USER,
    password: '12345678',
    status: 'paused',
    age: '28',
    avatar: '',
    email: 'megan.richards@example.com',
  },
  {
    id: 13,
    name: 'Oliver Scott',
    role: Role.USER,
    password: '12345678',
    status: 'active',
    age: '37',
    avatar: '',
    email: 'oliver.scott@example.com',
  },
  {
    id: 14,
    name: 'Grace Allen',
    role: Role.USER,
    password: '12345678',
    status: 'active',
    age: '30',
    avatar: '',
    email: 'grace.allen@example.com',
  },
  {
    id: 15,
    name: 'Noah Carter',
    role: Role.ADMIN,
    password: '12345678',
    status: 'paused',
    age: '31',
    avatar: '',
    email: 'noah.carter@example.com',
  },
  {
    id: 16,
    name: 'Ava Perez',
    role: Role.USER,
    password: '12345678',
    status: 'active',
    age: '29',
    avatar: '',
    email: 'ava.perez@example.com',
  },
  {
    id: 17,
    name: 'Liam Johnson',
    role: Role.USER,
    password: '12345678',
    status: 'active',
    age: '28',
    avatar: '',
    email: 'liam.johnson@example.com',
  },
  {
    id: 18,
    name: 'Sophia Taylor',
    role: Role.USER,
    password: '12345678',
    status: 'active',
    age: '27',
    avatar: '',
    email: 'sophia.taylor@example.com',
  },
  {
    id: 19,
    name: 'Lucas Harris',
    role: Role.USER,
    password: '12345678',
    status: 'paused',
    age: '32',
    avatar: '',
    email: 'lucas.harris@example.com',
  },
  {
    id: 20,
    name: 'Mia Robinson',
    role: Role.ADMIN,
    password: '12345678',
    status: 'active',
    age: '26',
    avatar: '',
    email: 'mia.robinson@example.com',
  },
];
